name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main
      - chore/deploy-netlify

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: yarn

      - name: Create Env
        run: |
          touch .env
          echo FIREBASE_API_KEY=${{secrets.FIREBASE_API_KEY}} >> .env
          echo FIREBASE_AUTH_DOMAIN=${{secrets.FIREBASE_AUTH_DOMAIN}} >> .env
          echo FIREBASE_PROJECT_ID=${{secrets.FIREBASE_PROJECT_ID}} >> .env
          echo FIREBASE_STORAGE_BUCKET=${{secrets.FIREBASE_STORAGE_BUCKET}} >> .env
          echo FIREBASE_MESSAGING_SENDER_ID=${{secrets.FIREBASE_MESSAGING_SENDER_ID}} >> .env
          echo FIREBASE_APP_ID=${{secrets.FIREBASE_APP_ID}} >> .env
          echo FIREBASE_MEASUREMENT_ID=${{secrets.FIREBASE_MEASUREMENT_ID}} >> .env
          echo FIREBASE_DATABASE_URL=${{secrets.FIREBASE_DATABASE_URL}} >> .env
          echo REACT_BASE_API_URL=${{secrets.REACT_BASE_API_URL}} >> .env

      - name: Build
        run: yarn build:prod

      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
